version: "3.8"

services:

  # ================================
  # VOTRE APP ML (prediction vin)
  # ================================
  app:
    build: .
    image: mirahasina/wine-quality:latest
    container_name: wine-prediction-app
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - DATA_PATH=/app/data/winequality-red.csv
      - MODEL_PATH=/app/src/model/random_forest_wine.pkl
      - SCALER_PATH=/app/src/model/scaler_wine.pkl
    ports:
      - "5000:5000"
    restart: always
    networks:
      - mlops-network

  # ================================
  # AIRFLOW - Orchestration ML
  # ================================
  postgres:
    image: postgres:15
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mlops-network
    restart: always

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow-webserver
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__SECRET_KEY=mlops-secret-key
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8085:8080"
    command: webserver
    restart: always
    networks:
      - mlops-network

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow-scheduler
    depends_on:
      - postgres
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: scheduler
    restart: always
    networks:
      - mlops-network

  airflow-init:
    image: apache/airflow:2.8.1
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname Admin --lastname MLOps --role Admin --email admin@mlops.com
               --username admin
               --password admin
               --firstname Admin
               --lastname MLOps
               --role Admin
               --email admin@mlops.com"
    networks:
      - mlops-network

volumes:
  postgres-data:

networks:
  mlops-network:
    driver: bridge
